### ISSUE TITLE
Releasing as a drupal.org project

### ISSUE THREAD

**Issue by shaisachs** [TFD7/TFD7#12]
Would it be possible to release this engine as a drupal.org project?  I'd be happy to help out with that process - whether it be with code tweaks or documentation, or whatever other items you think might be necessary.  If that's at all worthwhile to you, please feel free to get in touch!  I think this is a very worthwhile contribution to the community.

**Comment by renebakx** [comment]
I tried that, and i ran into the wall of rules and license issues, and just gave up.  There is a sandbox project on d.o. https://www.drupal.org/sandbox/ReneB/1075966

But if you now a way on how to get it done.. sure i'am game, cause I do believe that the whole community would benefit if it became a full project. Portability of template code could be a thing when migrating from D7 to D8.

**Comment by shaisachs** [comment]
Oh I see.  Thanks for letting me know!  Can you elaborate on what you mean by "rules and license issues?"

Thanks!

**Comment by renebakx** [comment]
Back then it was an issue that the Twig library itself used a different license then Drupal did, but I guess that issue is now fixed because of Twig being in core.

And the other issue was getting trough the checks with code formatting. I originally created TFD with PSR coding standards instead of the Drupal one. And that was a serious showstopper. 

Must give it a go again, could simply auto format with PHPStorm and hope that every goes smooth. I'am just not that good at following the rules and get very aggravated if people complain about a small issues like a newline or a . with a space etc.

**Comment by shaisachs** [comment]
Heh heh heh that figures.  Drupal coding standards holy wars are the best!  Thanks for the explanation.

**Comment by renebakx** [comment]
The good news is... this time it worked :)

As of today, it is a full project  https://www.drupal.org/project/tfd7

**Comment by shaisachs** [comment]
Woooo!!  Thanks so much!
