### ISSUE TITLE
Use namespaced twig paths for includes etc

### ISSUE THREAD

**Issue by davyrolink** [TFD7/TFD7#21]
Hi Rene,

Currently you added the possibility to include other twig files like:
```
{% include 'theme::point/to/template.twig.tpl' %}
```

It will be nice if we could use the default(twig/d8) namespaced twig paths like:
```
{% include '@theme/point/to/template.twig.tpl' %}
```

What's your opinion on this, would you be willing to merge a pull request for this?

Grt!

**Comment by renebakx** [comment]
That one is actually on my target list as well. I still regret the old :: syntax, but now have the issue that I must keep it alive or fix all the production sites.

I was thinking on fixing it in \TFD_Loader_Filesystem::findTemplate by checking if the template name has a @ instead of a :: and mapping that back to the old :: style of template loading.

So if you already did that, or in another way kept the backwards compatibility, yes I would love to merge that.

**Comment by davyrolink** [comment]
Ok, I already did that(in another way that kept the bc), see https://github.com/davyrolink/TFD7/commit/e4c45e20d6dc77963e41733e98df1ddd6aa9f9a7

But since this repo is out of sync with the one on drupal.org, maybe you could sync those first to avoid any conflicts? Or do you want to me to submit a issue+patch at drupal.org?

**Comment by renebakx** [comment]
sweet :) Just merged it into the development branch. Will prepare a new .xx release on D.O. next week. Must update the documentation and test it against one of the double extended themes first.

Thank you!..

**Comment by drupol** [comment]
Can we update the documentation for this please ?
