### ISSUE TITLE
I'm not able to include partial twig templates

### ISSUE THREAD

**Issue by defra91** [TFD7/TFD7#47]
I started using this library few weeks ago and everything was super until I found that I cannot include partial templates:

Main template
```
<div class="row">
  <!-- Package template -->
  {% for package in cofanetto.packages %}
    {% include 'bgift::nodes/partials/node--package_teaser.html' with {'package': package} %}
  {% endfor %}
  <!-- End Package template -->
</div>
```

Inlcuded partial template:

```
<div class="col-sm-4">
  ...
</div>
```

I keep getting the same error:

```
Could not find a cache key for template "nodes/partials/node--package_teaser.html" in "sites/all/themes/bgift/templates/nodes/node--gift-cofanetto_soggiorno.tpl.twig
```

Please, I'm stuck with this and it would be really nice to include partial templates.

Thanks in advance for your support.

**Comment by defra91** [comment]
Well after struggling for a while I managed to solve it by using a full path instead of relative path:

```
{% include 'sites/all/themes/bgift::nodes/partials/node--package_teaser.html' with {'package': package} %}
```

**Comment by renebakx** [comment]
Sorry for late comment ;( 

It should work without the entire path, however TFD assumes that templates are located in the /templates folder of a theme and are post fixed with .twig

For example
` {% include 'cwd::includes/favicon.tpl.twig' %}` 
Loads that template from
`sites/all/themes/cwd/templates/includes/favicon.tpl.twg`
