### ISSUE TITLE
Could not load PagerDefault_mysql

### ISSUE THREAD

**Issue by artempankov** [TFD7/TFD7#5]
With twig for drupal installed on Drupal 7 i get an error when viewing pages:

Exception: Could not load PagerDefault_mysql in UniversalClassLoader->findFile() (line 276 of /Users/stalker/Sites/acquia-drupal/sites/all/libraries/twig-for-drupal/autoloader/Autoloader.php).

Autoloader can't find such file for class.

What is wrong?

**Comment by victoriachan** [comment]
Hi,

Any news on this issue? I'm using the latest Master (as of Jul 12, 2015).

Thanks,
Victoria

**Comment by renebakx** [comment]
did you try it with the x-autoload module?  https://www.drupal.org/project/xautoload or with the build in autoloader. I'am wondering if I should fix the build in, or switch to xautoload as full dependency cause more project are using that autoloader in Drupal and it prevents autoloader inception.

**Comment by victoriachan** [comment]
Thanks for this. I have just managed to fix it by renaming NodeVisitor.php from Nodevisitor.php (from https://github.com/TFD7/TFD7/issues/10).

I am using xautoload. For some reason maybe because I already had the older version of Nodevisitor.php on my site's git repo, when I updated to your latest master, it didn't register the renaming. 

Somehow though the error didn't seem related at first glance, I'm not seeing this error anymore. Hope this helps someone else too.

Thanks for the good work!
